### PR TITLE
Fix right margin on TpNavigation_navbar.jinja2

### PR DESCRIPTION
**Pull request by Guddu327**
I have inserted a new mr-2 (right margin field on the button).

### CODE REVIEW

**Comment by jamesmccannon02** [comment]
Thanks for this. I'll test later and then commit.

**Comment by jamesmccannon02** [comment]
@Guddu327 Hi, this doesn't appear to work. Did you test it yourself?

**Comment by cp2004** [comment]
The `mr-2` property does not exist, OctoPrint uses Bootstrap 2

**Comment by jamesmccannon02** [comment]
@cp2004 Thanks for confirming, didn't believe it was but couldn't be sure

**Comment by jamesmccannon02** [comment]
This has been left uncommented on for a period of time

**Pull request closed without merging**
